spring:
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:pool:postgresql://aws-0-us-west-1.pooler.supabase.com:5432/postgres}
    username: ${SPRING_R2DBC_USERNAME:postgres.tuuxndxyhvjrnvqkgrma}
    password: ${SPRING_R2DBC_PASSWORD:UpfA3yGIo7CFFLyK}
